name: JSON Tokens Workflow

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tokens/studio.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      # Sets up Node.js environment to run your script.

    - name: Install dependencies
      run: npm install
      # If your script requires dependencies, install them.

    - name: Run build-tokens script
      run: node build-tokens.js
